name: Build

on: [push, workflow_dispatch]

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: LinqLover/create-image@master
        id: create-image
        with:
          prepare-script: ./scripts/prepareImage.st
      - uses: actions/upload-artifact@master
        with:
          name: image
          path: ${{ steps.create-image.outputs.bundle-path }}

  build-screenshots:
    needs: create-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: image
      - name: Build screenshots
        run: |
          unzip Squeak*.zip
          ./squeak.sh -headless $(realpath ./scripts/buildScreenshots.st)
          cp -r Squeak*.app/Contents/Resources/screenshots/ .
      - uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: screenshots/

  update-screenshots:
    needs:
      - build-screenshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - run: rm -rf screenshots/
      - uses: actions/download-artifact@master
        with:
          name: screenshots
          path: screenshots/
      - uses: EndBug/add-and-commit@v9
        id: commit
        with:
          default_author: github_actions
          add: screenshots/
          message: "Add screenshots for ${{ github.sha }}"
          push: ${{ github.ref == 'refs/heads/main' }}
      - uses: actions/setup-node@v3
        if: ${{ steps.commit.outputs.committed == 'true' }}  # only required for commit comment below
        with:
          node-version: 16
      - run: |
          npm install -g nodegit@v0.28.0-alpha.18  # https://github.com/nodegit/nodegit/issues/1840
          npm link nodegit
        if: ${{ steps.commit.outputs.committed == 'true' }}  # only required for commit comment below
      - if: ${{ steps.commit.outputs.committed == 'true' }}  # no changes -> no commit -> no comment
        name: Create commit comment for screenshot diff
        uses: actions/github-script@v6
        with:
          script: |
            const nodegit = require('nodegit')
            const repo = await nodegit.Repository.open('.')
            const commit = await repo.getCommit('${{ steps.commit.outputs.commit_long_sha }}')
            const patches = (await Promise.all((await commit.getDiff()).map(diff => diff.patches()))).flatMap(patch => patch)
            const screenshotBuilderUrl = `${{ github.server_url }}/${{ github.repository }}/tree/HEAD/packages/TraceDebuggerJobs.package/TDBScreenshotBuilder.class`
            const genericScreenshotUrl = `${{ github.server_url }}/${{ github.repository }}/tree/gh-pages`
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `## Changed Screenshots

              This commit caused [a change of ${patches.length} ${patches.length === 1 ? 'screenshot' : 'screenshots'}](${${{ steps.commit.outputs.pushed }} ? `${{ github.server_url }}/${{ github.repository }}/commit/${commit.sha()}` : screenshotBuilderUrl}):

              ${patches
                .map(patch =>
                  `- [${patch.newFile().path()}](${
                    ${{ steps.commit.outputs.pushed }}
                      ? `${{ github.server_url }}/${{ github.repository }}/commits/${commit.sha()}/files/${patch.newFile().path()}#diff-${patch.newFile().id()}`
                      : `${genericScreenshotUrl}/${patch.newFile().path()}`
                  })`)
                .join('\n')}
              `,
            })

  release-image:
    needs: create-image
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"
      - uses: actions/download-artifact@master
        with:
          name: image
      - run: mv Squeak*.zip TraceDebugger-${{ steps.date.outputs.date }}.zip
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: untagged-${{ steps.date.outputs.date }}
          body: ${{ github.event.head_commit.message }}
          files: TraceDebugger-*.zip
          fail_on_unmatched_files: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
