name: Tests & Benchmarks

on: [push, workflow_dispatch]

env:
  SMALLTALK_IMAGE: Squeak64-Trunk
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: smalltalkci
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ env.SMALLTALK_IMAGE }}
      - id: download-vm
        name: Download latest VM
        run: scripts/download_vm.sh
      - name: Run tests
        run: smalltalkci -s "${{ steps.smalltalkci.outputs.smalltalk-image }}" --vm "${{ steps.download-vm.outputs.vm-path }}" tests.smalltalk.ston
        timeout-minutes: 15
        env:
          # for uploading coverage reports
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  benchmarks:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - uses: actions/checkout@v2
      - id: smalltalkci
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ env.SMALLTALK_IMAGE }}
      - id: download-vm
        name: Download latest VM
        run: scripts/download_vm.sh
      - name: Run benchmarks
        run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }} --vm "${{ steps.download-vm.outputs.vm-path }}" benchmarks.smalltalk.ston
        timeout-minutes: 15
        env:
          TDB_BENCHMARK_RESULTS_PATH: ${{ runner.temp }}/benchmark-data.json
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark data
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: ${{ runner.temp }}/benchmark-data.json
          auto-push: true
          gh-pages-branch: gh-pages
          comment-always: false
          fail-on-alert: false
          alert-threshold: "150%"
          github-token: ${{ secrets.GITHUB_TOKEN }}
